/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    3dContainer: typeof import('./components/common/3dContainer.vue')['default']
    AlertNotification: typeof import('./components/common/AlertNotification.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BottomBar: typeof import('./components/common/BottomBar.vue')['default']
    Camera: typeof import('./components/common/Camera.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    Loader: typeof import('./components/common/Loader.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    LoginView: typeof import('./components/views/auth/LoginView.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RegisterView: typeof import('./components/views/auth/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanDetails: typeof import('./components/views/ScanDetails.vue')['default']
    ScanHistory: typeof import('./components/views/ScanHistory.vue')['default']
    ScrollDown: typeof import('./components/common/ScrollDown.vue')['default']
  }
}
